#!/bin/sh

set -e

AGENT=IPaddr2

cleanup () {
  ocft clean $AGENT
}

trap "cleanup" 0 2 3 15

IFACE=$(ip route show 0/0 | head -n 1 | cut -d ' ' -f 5)
echo "IFACE detected as $IFACE"
sed "s|eth0|$IFACE|g" /usr/share/resource-agents/ocft/configs/$AGENT > $AUTOPKGTEST_TMP/$AGENT

mkdir -p /run/resource-agents

printf "\n\n\ncall OCFT make for $AGENT\n"
ocft make -d $AUTOPKGTEST_TMP $AGENT

printf "\n\n\ncall OCFT test for $AGENT\n"
ocft test -v $AGENT
