#!/bin/sh

set -e

AGENT=$1

cleanup () {
  ocft clean $AGENT
}

trap "cleanup" 0 2 3 15

mkdir -p /run/resource-agents

printf "\n\n\ncall OCFT make for $AGENT\n"
ocft make $AGENT

printf "\n\n\ncall OCFT test for $AGENT\n"
ocft test -v $AGENT
