#!/bin/sh
#
### BEGIN INIT INFO
# Short-Description: Monitor virtual services provided by LVS.
# Provides:          ldirectord
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO
#
# Author: Horms <horms@verge.net.au>
#
# Debian init script for ldirectord
#

NAME=ldirectord
DAEMON="/usr/sbin/$NAME"
CONFIG="/etc/default/$NAME"

test -x $DAEMON || exit 0

test -x /var/lock/subsys || mkdir -p /var/lock/subsys

. /lib/lsb/init-functions

CONFIG_FILE=""
[ -f "$CONFIG" ] && . "$CONFIG"
CONFIG_FILE="${CONFIG_FILE:=/etc/ldirectord.cf}"

test -f ${CONFIG_FILE} 
RC=$?
if [ $RC -ne 0 ] ; then
	log_warning_msg "No configuration file found, doing nothing."
	exit 0   
fi

case "$1" in
	start|stop|restart|try-restart|status|reload|force-reload)
		log_daemon_msg "Running $NAME" "$1"
		"$DAEMON" "$CONFIG_FILE" $1
		RC=$?
		log_end_msg $RC
		exit $RC
	;;
	*)
		echo "Usage: /etc/init.d/$NAME" \
			"{start|stop|restart|try-restart|status|reload|force-reload}" >&2
    	exit 1
	;;
esac
